### ISSUE TITLE
Route error causes add post form not to load

### ISSUE THREAD

**Issue by rayGreycloud** [rulonsw/ChainReact#39]
**Describe the bug**
Attempting to navigate to the add post form results in a full post view that fails to load.
Review of network activity shows attempted data fetch for full post view
Inspection of element in browser shows class name from FullPostView component

**To Reproduce**
1. Go to current homepage
2. Click on Add Post button
3. Page view changes to full post view template instead of add post form
4. Page stuck on loading state

**Expected behavior**
change of page view to add post form

**Comment by rayGreycloud** [comment]
The path for the new post route in `App.js`  has typo;
Should be:  `/posts/new`

**Comment by rulonsw** [comment]
Fixed by #41
