### ISSUE TITLE
Part of Add post form pushed offscreen left

### ISSUE THREAD

**Issue by rayGreycloud** [rulonsw/ChainReact#40]
**Describe the bug**
Part of the add post form is pushed off screen left

**To Reproduce**
1. Click on Add Post button
2. Part of form title is visibly cut off on left side.

**Comment by rayGreycloud** [comment]
Problem stems from routing structure in App and location of the Footer component
- Header and Footer need to be same width and should inherit from same parent to be properly responsive
- Header should not be wrapping Switch and routes, should come before with no children
- Footer should be located in `App.js ` after Switch, not inside Header
Solution: re-factor Header and App as indicated above.

**Comment by rulonsw** [comment]
Fixed by #41
